# Generated by Django 4.2 on 2023-04-19 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_currencyrate_useraccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='amount',
            new_name='balance',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='updated_at',
        ),
    ]
