# Generated by Django 4.2 on 2023-04-19 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_rename_amount_useraccount_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='currency',
        ),
    ]
