# Generated by Django 4.2 on 2023-04-20 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_useraccount_primary_bank_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='primary_bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_account_of', to='bank.bankaccount'),
        ),
    ]
