# Generated by Django 4.2 on 2023-05-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0011_alter_transaction_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='secret_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
