# Generated by Django 4.2 on 2023-05-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0012_useraccount_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='otp_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
