# Generated by Django 4.2 on 2023-05-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0013_useraccount_otp_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
