name: Django CI

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]

jobs:
  build:
    - uses: actions/checkout@v2
    - name: Setup Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        coverage run manage.py test
        coverage report
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
        
